version: '3.8'

services:
  database:
    container_name: 'mysql-container'
    restart: always
    image: 'mysql:8.0'
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: sandbox
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      # 'host':'MySQL Port running inside container'
      - '3306:3306'
    volumes:
      - './volume/data:/var/lib/mysql'
      - './volume/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './volume/sql:/docker-entrypoint-initdb.d'
volumes:
  volume:
